version: '3'
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './data:/home/dynamodblocal/data'
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    # TODO: add production specific variables, configurations etc later
